### PR TITLE
12.0 afc 1279

### PR DESCRIPTION
**Pull request by rupareliyahemangi145**

### CODE REVIEW

**Comment by FredrikArvas** [comment]
Please merge this to Fenix-Dev-branch.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 
**Please merge this to Fenix-Dev-branch**
Is this comment for me? Should I create new PR for Dev-12.0-Fenix_Sprint-02 and merge?

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
yes. 
The reason is that I have been unclear with what branch we want the new code in. 
(Basic principle= All code for the Fenix project => Fenix-branch).

Please change/make a new PR.
Thanks

**Comment by rupareliyahemangi145** [comment]
Ok Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created new PR https://github.com/vertelab/odoo-hr/pull/20 for Fenix branch. Closing this PR as created new PR.

**Pull request closed without merging**
